#!/usr/bin/env python3
"""Mirror the overlay's default strings into every locale AOSP shadows them in.

AOSP Settings declares the face enrollment copy and ships it empty, not only in
values/ but in 85 translated directories as well. A locale qualified value is a
better config match than an unqualified one, so those empties beat an override
that only lives in values/ and the page stays blank for anyone whose locale AOSP
translated. Emitting the same text under each of those qualifiers is what makes
the override reachable.

The text is English everywhere, which is a fallback rather than a translation;
without it the alternative is a blank page.

Run from the tree root.
"""

import os
import re
import sys

SETTINGS = "packages/apps/Settings"
OVERLAY = "device/google/yogi/overlay/SettingsOverlayLineageYogi/res"
HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
     SPDX-FileCopyrightText: The LineageOS Project
     SPDX-License-Identifier: Apache-2.0

     Generated by tools/gen-face-locale-overrides.py. AOSP ships these strings
     empty under this qualifier, which outranks the unqualified value, so the
     text has to be repeated here to be reachable. English is a fallback.
-->
<resources>
"""


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def main():
    src = os.path.join(OVERLAY, "values", "strings.xml")
    ours = dict(re.findall(r'<string name="([A-Za-z0-9_]+)">(.*?)</string>',
                           read(src), re.S))
    if not ours:
        sys.exit("no strings found in " + src)
    print("source strings: %d" % len(ours))

    locales = {}
    for base in (SETTINGS + "/res", SETTINGS + "/res-product"):
        if not os.path.isdir(base):
            continue
        for d in sorted(os.listdir(base)):
            if not d.startswith("values-"):
                continue
            f = os.path.join(base, d, "strings.xml")
            if not os.path.exists(f):
                continue
            body = read(f)
            here = set(re.findall(r'<string name="([A-Za-z0-9_]+)"', body))
            hit = sorted(n for n in ours if n in here)
            if hit:
                locales.setdefault(d, set()).update(hit)

    written = 0
    for d, names in sorted(locales.items()):
        out_dir = os.path.join(OVERLAY, d)
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, "strings.xml"), "w", encoding="utf-8") as fh:
            fh.write(HEADER)
            for n in sorted(names):
                fh.write('    <string name="%s">%s</string>\n' % (n, ours[n]))
            fh.write("</resources>\n")
        written += 1
    print("wrote %d locale directories" % written)
    total = sum(len(v) for v in locales.values())
    print("total overridden entries: %d" % total)


if __name__ == "__main__":
    main()
